/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Components.Background;
import Controller.CtrUser;
import java.awt.Color;

/**
 *
 * @author ASUS TUF A15
 */
public class FrmAddUser extends javax.swing.JFrame {

    /**
     * Creates new form FrmAddUser
     */
    Background back = new Background();
    CtrUser ctrUser;
    public FrmAddUser() {
        this.setContentPane(back);
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setExtendedState(FrmUserBook.MAXIMIZED_BOTH);
        ctrUser = new CtrUser();
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBorder1 = new Components.PanelBorder();
        jPanel1 = new javax.swing.JPanel();
        TXT_name = new Components.TextField();
        TXT_TypeUser = new Components.TextField();
        TXT_codeUser = new Components.TextField();
        TXT_last_name = new Components.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXT_email = new Components.TextField();
        TXT_grade = new Components.Select();
        jPanel2 = new javax.swing.JPanel();
        BTN_back_menu = new javax.swing.JButton();
        BTN_back_menu1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelBorder1.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder1.setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);
        jPanel1.add(TXT_name);
        TXT_name.setBounds(700, 200, 500, 50);
        jPanel1.add(TXT_TypeUser);
        TXT_TypeUser.setBounds(110, 120, 1090, 50);
        jPanel1.add(TXT_codeUser);
        TXT_codeUser.setBounds(110, 41, 500, 50);
        jPanel1.add(TXT_last_name);
        TXT_last_name.setBounds(110, 200, 550, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Codigo Usuario");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 20, 110, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setText("Tipo de Usuario");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 100, 110, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("Apellido");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 180, 110, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(710, 180, 110, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel7.setText("Correo");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 330, 110, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setText("Grado");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 260, 110, 16);
        jPanel1.add(TXT_email);
        TXT_email.setBounds(110, 350, 1100, 50);

        TXT_grade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primaria", "Secundaria", "bachillerato", " " }));
        jPanel1.add(TXT_grade);
        TXT_grade.setBounds(115, 280, 1090, 40);

        panelBorder1.add(jPanel1);
        jPanel1.setBounds(0, 100, 1300, 420);

        jPanel2.setOpaque(false);

        BTN_back_menu.setBackground(new java.awt.Color(9, 57, 134));
        BTN_back_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTN_back_menu.setForeground(new java.awt.Color(255, 255, 255));
        BTN_back_menu.setText("Agregar");
        BTN_back_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_back_menuActionPerformed(evt);
            }
        });

        BTN_back_menu1.setBackground(new java.awt.Color(9, 57, 134));
        BTN_back_menu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTN_back_menu1.setForeground(new java.awt.Color(255, 255, 255));
        BTN_back_menu1.setText("Regresar");
        BTN_back_menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_back_menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1164, Short.MAX_VALUE)
                .addComponent(BTN_back_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(BTN_back_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1169, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(BTN_back_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(BTN_back_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        panelBorder1.add(jPanel2);
        jPanel2.setBounds(0, 520, 1300, 75);

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 57, 134));
        jLabel1.setText("Agregar Usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelBorder1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1300, 100);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 1300;
        gridBagConstraints.ipady = 600;
        getContentPane().add(panelBorder1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_back_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_back_menuActionPerformed
        ctrUser.addUser(this);
    }//GEN-LAST:event_BTN_back_menuActionPerformed

    private void BTN_back_menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_back_menu1ActionPerformed
        ctrUser.returnManagement(this);
    }//GEN-LAST:event_BTN_back_menu1ActionPerformed
    /*Metodos get y set*/
    public String getTypeUser() {
            return TXT_TypeUser.getText();
        }
    
    public String getCodeUser() {
        return TXT_codeUser.getText();
    }
    
    public String getEmail() {
        return TXT_email.getText();
    }
    
    public String getGrade() {
        return TXT_grade.getSelectedItem().toString();  // Supone que Select tiene este método
    }
    
    public String getLastName() {
        return TXT_last_name.getText();
    }
    
    public String getName() {
        return TXT_name.getText();
    }
    
    /*Metodos get y set*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAddUser().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_back_menu;
    private javax.swing.JButton BTN_back_menu1;
    private Components.TextField TXT_TypeUser;
    private Components.TextField TXT_codeUser;
    private Components.TextField TXT_email;
    private Components.Select TXT_grade;
    private Components.TextField TXT_last_name;
    private Components.TextField TXT_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private Components.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
