/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Components.Background;
import Controller.Ctrlogin;
import Modelo.User;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ASUS TUF A15
 */
public class FrmLogIn extends javax.swing.JFrame {
    Background back = new Background();
    private String realPassword = "";
    
    Ctrlogin log;
    /**
     * Creates new form LogIn
     */
    public FrmLogIn() {
        setIconImage(new ImageIcon(getClass().getResource("/img/iconof.png")).getImage());
        this.setContentPane(back);
        initComponents();
        this.setExtendedState(FrmLogIn.MAXIMIZED_BOTH);
        User user = new User();
        FrmMenuOptions frmMenu= new FrmMenuOptions();
        log= new Ctrlogin( user,this,frmMenu);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBorder2 = new Components.PanelBorder();
        PA_login_form1 = new javax.swing.JPanel();
        login_title1 = new javax.swing.JLabel();
        JL_user1 = new javax.swing.JLabel();
        JL_password1 = new javax.swing.JLabel();
        BTN_login = new javax.swing.JButton();
        TF_username = new javax.swing.JTextField();
        TF_password = new javax.swing.JPasswordField();
        img_acces1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelBorder2.setBackground(new java.awt.Color(227, 227, 227));

        PA_login_form1.setBackground(new java.awt.Color(255, 253, 255));
        PA_login_form1.setOpaque(false);

        login_title1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        login_title1.setText("Login");

        JL_user1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        JL_user1.setText("Usuario");

        JL_password1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        JL_password1.setText("Contraseña");

        BTN_login.setBackground(new java.awt.Color(9, 57, 134));
        BTN_login.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        BTN_login.setForeground(new java.awt.Color(255, 255, 255));
        BTN_login.setText("Ingresar");
        BTN_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_loginActionPerformed(evt);
            }
        });

        TF_username.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        TF_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TF_password.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        TF_password.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout PA_login_form1Layout = new javax.swing.GroupLayout(PA_login_form1);
        PA_login_form1.setLayout(PA_login_form1Layout);
        PA_login_form1Layout.setHorizontalGroup(
            PA_login_form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PA_login_form1Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(login_title1)
                .addGap(180, 180, 180))
            .addGroup(PA_login_form1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PA_login_form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_password, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addGroup(PA_login_form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TF_username)
                        .addComponent(BTN_login, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                        .addComponent(JL_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JL_user1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PA_login_form1Layout.setVerticalGroup(
            PA_login_form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PA_login_form1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(login_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(JL_user1)
                .addGap(18, 18, 18)
                .addComponent(TF_username, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JL_password1)
                .addGap(18, 18, 18)
                .addComponent(TF_password, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(BTN_login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        img_acces1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_acc1.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(PA_login_form1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(img_acces1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PA_login_form1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(img_acces1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = -14.0;
        getContentPane().add(panelBorder2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_loginActionPerformed
        log.input();
    }//GEN-LAST:event_BTN_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ;

                new FrmLogIn().setVisible(true);
            }
        });
    }
    
    public String getUser(){
        
        return TF_username.getText();
    }
    public String getPassword(){

        return TF_password.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_login;
    private javax.swing.JLabel JL_password1;
    private javax.swing.JLabel JL_user1;
    private javax.swing.JPanel PA_login_form1;
    private javax.swing.JPasswordField TF_password;
    private javax.swing.JTextField TF_username;
    private javax.swing.JLabel img_acces1;
    private javax.swing.JLabel login_title1;
    private Components.PanelBorder panelBorder2;
    // End of variables declaration//GEN-END:variables

    
  
}