/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.Ctrlogin;
import Modelo.User;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ASUS TUF A15
 */
public class FrmLogIn extends javax.swing.JFrame {
    Background back = new Background();
    
    Ctrlogin log;
    /**
     * Creates new form LogIn
     */
    public FrmLogIn() {
        this.setContentPane(back);
        initComponents();
        this.setExtendedState(FrmLogIn.MAXIMIZED_BOTH);
        User user = new User();
        FrmMenuOptions frmMenu= new FrmMenuOptions();
        log= new Ctrlogin( user,this,frmMenu);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PA_login = new javax.swing.JPanel();
        PA_login_form = new javax.swing.JPanel();
        login_title = new javax.swing.JLabel();
        JL_user = new javax.swing.JLabel();
        TF_username = new javax.swing.JTextField();
        JL_password = new javax.swing.JLabel();
        TF_password = new javax.swing.JTextField();
        BTN_login = new javax.swing.JButton();
        img_acces = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PA_login.setBackground(new java.awt.Color(255, 255, 255));
        PA_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PA_login.setMinimumSize(new java.awt.Dimension(32767, 32767));

        PA_login_form.setBackground(new java.awt.Color(255, 253, 255));

        login_title.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        login_title.setText("Login");

        JL_user.setText("Usuario");

        JL_password.setText("Contraseña");

        TF_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_passwordActionPerformed(evt);
            }
        });

        BTN_login.setBackground(new java.awt.Color(9, 57, 134));
        BTN_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTN_login.setForeground(new java.awt.Color(255, 255, 255));
        BTN_login.setText("Ingresar");
        BTN_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PA_login_formLayout = new javax.swing.GroupLayout(PA_login_form);
        PA_login_form.setLayout(PA_login_formLayout);
        PA_login_formLayout.setHorizontalGroup(
            PA_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PA_login_formLayout.createSequentialGroup()
                .addGroup(PA_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PA_login_formLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(PA_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JL_user, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_password, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_username)
                            .addComponent(TF_password)
                            .addComponent(BTN_login, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)))
                    .addGroup(PA_login_formLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(login_title)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PA_login_formLayout.setVerticalGroup(
            PA_login_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PA_login_formLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JL_user)
                .addGap(18, 18, 18)
                .addComponent(TF_username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JL_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TF_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BTN_login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        img_acces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_acc1.png"))); // NOI18N

        javax.swing.GroupLayout PA_loginLayout = new javax.swing.GroupLayout(PA_login);
        PA_login.setLayout(PA_loginLayout);
        PA_loginLayout.setHorizontalGroup(
            PA_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PA_loginLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(PA_login_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_acces, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        PA_loginLayout.setVerticalGroup(
            PA_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PA_loginLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PA_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img_acces, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(PA_login_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        img_acces.getAccessibleContext().setAccessibleName("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(PA_login, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_loginActionPerformed
        log.input();
    }//GEN-LAST:event_BTN_loginActionPerformed

    private void TF_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ;

                new FrmLogIn().setVisible(true);
            }
        });
    }
    
    public String getUser(){
        return TF_username.getText();
    }
    public String getPassword(){
        return TF_password.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_login;
    private javax.swing.JLabel JL_password;
    private javax.swing.JLabel JL_user;
    private javax.swing.JPanel PA_login;
    private javax.swing.JPanel PA_login_form;
    private javax.swing.JTextField TF_password;
    public javax.swing.JTextField TF_username;
    private javax.swing.JLabel img_acces;
    private javax.swing.JLabel login_title;
    // End of variables declaration//GEN-END:variables

    
  
}
