/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Components.Background;
import Controller.CtrMenuOptions;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author ASUS TUF A15
 */
public class FrmMenuOptions extends javax.swing.JFrame {

    /**
     * Creates new form MenuOptions
     */
    CtrMenuOptions ctrM ;
    Background back= new Background();
    public FrmMenuOptions() {
        this.setContentPane(back);
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setExtendedState(FrmMenuOptions.MAXIMIZED_BOTH);
        
        back.BackgroundTrasparent(BTN_deliver);
        back.BackgroundTrasparent(BTN_purchase);
        back.BackgroundTrasparent(BTN_manage);
        ctrM= new CtrMenuOptions(this);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBorder1 = new Components.PanelBorder();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        panelBorder2 = new Components.PanelBorder();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelBorder3 = new Components.PanelBorder();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelBorder4 = new Components.PanelBorder();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BTN_purchase = new javax.swing.JButton();
        BTN_deliver = new javax.swing.JButton();
        BTN_manage = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelBorder1.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder1.setLayout(null);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 57, 134));
        jLabel1.setText("Sistema de biblioteca");
        jPanel4.add(jLabel1, new java.awt.GridBagConstraints());

        panelBorder1.add(jPanel4);
        jPanel4.setBounds(0, 0, 1300, 120);

        jPanel11.setBackground(new java.awt.Color(217, 217, 217));
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridBagLayout());

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder2.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adquirir.png"))); // NOI18N
        panelBorder2.add(jLabel5);
        jLabel5.setBounds(30, 20, 90, 90);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Adquirir");
        panelBorder2.add(jLabel20);
        jLabel20.setBounds(40, 120, 70, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weightx = 10.0;
        jPanel11.add(panelBorder2, gridBagConstraints);

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder3.setLayout(null);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/entregar.png"))); // NOI18N
        panelBorder3.add(jLabel21);
        jLabel21.setBounds(30, 20, 110, 100);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Entregar");
        panelBorder3.add(jLabel22);
        jLabel22.setBounds(40, 120, 80, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weightx = 10.0;
        jPanel11.add(panelBorder3, gridBagConstraints);

        panelBorder4.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder4.setLayout(null);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion.png"))); // NOI18N
        panelBorder4.add(jLabel23);
        jLabel23.setBounds(30, 20, 90, 90);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Gestion");
        panelBorder4.add(jLabel24);
        jLabel24.setBounds(40, 120, 70, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weightx = 10.0;
        jPanel11.add(panelBorder4, gridBagConstraints);

        panelBorder1.add(jPanel11);
        jPanel11.setBounds(0, 120, 1350, 320);

        jPanel5.setBackground(new java.awt.Color(217, 217, 217));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridBagLayout());

        BTN_purchase.setBackground(new java.awt.Color(242, 242, 242));
        BTN_purchase.setOpaque(isVisible());
        BTN_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_purchaseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weightx = 10.0;
        jPanel5.add(BTN_purchase, gridBagConstraints);

        BTN_deliver.setBackground(new java.awt.Color(242, 242, 242));
        BTN_deliver.setOpaque(isVisible());
        BTN_deliver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_deliverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weightx = 10.0;
        jPanel5.add(BTN_deliver, gridBagConstraints);

        BTN_manage.setBackground(new java.awt.Color(242, 242, 242));
        BTN_manage.setOpaque(isVisible());
        BTN_manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_manageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weightx = 10.0;
        jPanel5.add(BTN_manage, gridBagConstraints);

        panelBorder1.add(jPanel5);
        jPanel5.setBounds(0, 120, 1350, 320);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(9, 57, 134));
        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 103, 72, 30);

        panelBorder1.add(jPanel1);
        jPanel1.setBounds(0, 440, 1300, 150);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 1300;
        gridBagConstraints.ipady = 600;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 6, 0);
        getContentPane().add(panelBorder1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_purchaseActionPerformed
        ctrM.purchaseUser();
    }//GEN-LAST:event_BTN_purchaseActionPerformed

    private void BTN_deliverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_deliverActionPerformed
        ctrM.loan();
    }//GEN-LAST:event_BTN_deliverActionPerformed

    private void BTN_manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_manageActionPerformed
        ctrM.menuManagement();
    }//GEN-LAST:event_BTN_manageActionPerformed

    //Trasparencia boton
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_deliver;
    private javax.swing.JButton BTN_manage;
    private javax.swing.JButton BTN_purchase;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private Components.PanelBorder panelBorder1;
    private Components.PanelBorder panelBorder2;
    private Components.PanelBorder panelBorder3;
    private Components.PanelBorder panelBorder4;
    // End of variables declaration//GEN-END:variables
}
