/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Components.Background;
import Components.ScrollBar;
import Controller.CtrUser;
import Controller.CtrUserBooks;
import Modelo.UserBook;
import java.awt.Color;
import java.text.SimpleDateFormat;

/**
 *
 * @author ASUS TUF A15
 */
public class FrmUserBook extends javax.swing.JFrame {

    /**
     * Creates new form MenuOptions
     */
    private CtrUserBooks ctrUserBooks;
    CtrUser ctrUser;
    Background back = new Background();
    public FrmUserBook(CtrUserBooks ctrUserBooks) {
        this.setContentPane(back);
        initComponents();
        this.ctrUserBooks= ctrUserBooks;
        
        this.getContentPane().setBackground(Color.white);
        this.setExtendedState(FrmUserBook.MAXIMIZED_BOTH);
        JSCROLL_user_book.getViewport().setBackground(Color.WHITE);
        JSCROLL_user_book.setVerticalScrollBar(new ScrollBar());
        this.ctrUserBooks.loadSelectedBooksTableInto(JTable_User_book);
        ctrUser = new CtrUser();
        this.ctrUserBooks.getDate(TXT_Date);
        this.ctrUserBooks.setDateDelivery(RSDate);
        this.ctrUserBooks.mostrar(this);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBorder1 = new Components.PanelBorder();
        jPanel1 = new javax.swing.JPanel();
        BTN_loan = new javax.swing.JButton();
        BTN_back_book = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        TXT_Date = new Components.TextField();
        TF_name_user = new Components.TextField();
        TF_last_name_user = new Components.TextField();
        TF_mail_user = new Components.TextField();
        panelBorder2 = new Components.PanelBorder();
        JSCROLL_user_book = new javax.swing.JScrollPane();
        JTable_User_book = new Components.TableModel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RSDate = new rojeru_san.componentes.RSDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelBorder1.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder1.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setLayout(null);

        BTN_loan.setBackground(new java.awt.Color(9, 57, 134));
        BTN_loan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTN_loan.setForeground(new java.awt.Color(255, 255, 255));
        BTN_loan.setText("Confirmar");
        BTN_loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_loanActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_loan);
        BTN_loan.setBounds(1188, 0, 120, 40);

        BTN_back_book.setBackground(new java.awt.Color(9, 57, 134));
        BTN_back_book.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTN_back_book.setForeground(new java.awt.Color(255, 255, 255));
        BTN_back_book.setText("Cancelar");
        BTN_back_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_back_bookActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_back_book);
        BTN_back_book.setBounds(30, 10, 100, 40);

        panelBorder1.add(jPanel1);
        jPanel1.setBounds(0, 540, 1350, 50);

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setLayout(null);

        TXT_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_DateActionPerformed(evt);
            }
        });
        jPanel2.add(TXT_Date);
        TXT_Date.setBounds(980, 30, 240, 41);
        jPanel2.add(TF_name_user);
        TF_name_user.setBounds(150, 91, 500, 50);
        jPanel2.add(TF_last_name_user);
        TF_last_name_user.setBounds(720, 91, 500, 50);

        TF_mail_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_mail_userActionPerformed(evt);
            }
        });
        jPanel2.add(TF_mail_user);
        TF_mail_user.setBounds(150, 170, 500, 50);

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        JSCROLL_user_book.setBorder(null);

        JTable_User_book.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"fdfdf", null, null, null},
                {"dfdf", null, null, null},
                {"vvvv", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JSCROLL_user_book.setViewportView(JTable_User_book);
        if (JTable_User_book.getColumnModel().getColumnCount() > 0) {
            JTable_User_book.getColumnModel().getColumn(0).setResizable(false);
            JTable_User_book.getColumnModel().getColumn(1).setResizable(false);
            JTable_User_book.getColumnModel().getColumn(2).setResizable(false);
            JTable_User_book.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSCROLL_user_book, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JSCROLL_user_book, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        jPanel2.add(panelBorder2);
        panelBorder2.setBounds(150, 250, 1070, 180);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("Apellido");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(730, 70, 120, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("Fecha de devolucion");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(730, 140, 160, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 66, 120, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setText("Correo");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(160, 140, 120, 20);

        RSDate.setColorBackground(new java.awt.Color(9, 57, 134));
        RSDate.setColorButtonHover(new java.awt.Color(204, 204, 204));
        RSDate.setColorDiaActual(new java.awt.Color(0, 51, 204));
        RSDate.setColorForeground(new java.awt.Color(0, 0, 0));
        RSDate.setFormatoFecha("yyyy-MM-dd");
        jPanel2.add(RSDate);
        RSDate.setBounds(730, 170, 480, 40);

        panelBorder1.add(jPanel2);
        jPanel2.setBounds(0, 90, 1350, 450);

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(9, 57, 134));
        jLabel6.setText("Sistema de Biblioteca");
        jPanel3.add(jLabel6);

        panelBorder1.add(jPanel3);
        jPanel3.setBounds(0, 10, 1350, 80);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1350;
        gridBagConstraints.ipady = 600;
        getContentPane().add(panelBorder1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_loanActionPerformed
        // TODO add your handling code here:
        ctrUserBooks.insertloan(this);
        
        ctrUser.menu();
    }//GEN-LAST:event_BTN_loanActionPerformed

    private void BTN_back_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_back_bookActionPerformed
        ctrUserBooks.backpurchaseBook(ctrUserBooks, this);
    }//GEN-LAST:event_BTN_back_bookActionPerformed

    private void TF_mail_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_mail_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_mail_userActionPerformed

    private void TXT_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_DateActionPerformed

    //Get y Set
    public String getDateDelivery() {
    // Obtener la fecha seleccionada del RSDateChooser
    java.util.Date selectedDate = RSDate.getDatoFecha();

    // Verificar si la fecha es nula
    if (selectedDate == null) {
        return "";  // Retornar una cadena vacía si no se ha seleccionado una fecha
    }

    // Crear un formato de fecha
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

    // Devolver la fecha formateada como String
    return formatter.format(selectedDate);
}
    
    public String getDate() {
        return TXT_Date.getText();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserBook userbook = new UserBook();
                CtrUserBooks ctrUserBooks = new CtrUserBooks(userbook);
                new FrmUserBook(ctrUserBooks).setVisible(true);
            }
        });
    }
    public javax.swing.JTable getJTableBook() {
        return JTable_User_book;
    }
    
    // Getter y Setter para el campo de nombre
    public String getNameUser() {
        return TF_name_user.getText();
    }

    public void setNameUser(String name) {
        TF_name_user.setText(name);
    }

    // Getter y Setter para el campo de apellido
    public String getLastNameUser() {
        return TF_last_name_user.getText();
    }

    public void setLastNameUser(String lastName) {
        TF_last_name_user.setText(lastName);
    }

    // Getter y Setter para el campo de correo
    public String getMailUser() {
        return TF_mail_user.getText();
    }

    public void setMailUser(String mail) {
        TF_mail_user.setText(mail);
    }


    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_back_book;
    private javax.swing.JButton BTN_loan;
    private javax.swing.JScrollPane JSCROLL_user_book;
    private Components.TableModel JTable_User_book;
    private rojeru_san.componentes.RSDateChooser RSDate;
    private Components.TextField TF_last_name_user;
    private Components.TextField TF_mail_user;
    private Components.TextField TF_name_user;
    private Components.TextField TXT_Date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private Components.PanelBorder panelBorder1;
    private Components.PanelBorder panelBorder2;
    // End of variables declaration//GEN-END:variables
}
